[package]
distribution = "{{BAL_VERSION}}"
org = "ballerinax"
name = "{{MODULE_NAME_CC}}"
version = "{{MODULE_VERSION}}"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
# icon = "icon.png" # TODO: update icon.png
repository = "https://github.com/ballerina-platform/{{REPO_NAME}}"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
